CREATE TABLESPACE R6_DAT
DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_dat.dbf' SIZE 64M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
;

CREATE TABLESPACE R6_LOB
DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_lob.dbf' SIZE 64M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
;

CREATE TABLESPACE R6_IDX
DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_idx.dbf' SIZE 64M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
;

CREATE TEMPORARY TABLESPACE R6_TMP
TEMPFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_tmp.dbf' SIZE 64M
EXTENT MANAGEMENT LOCAL
;

ALTER DATABASE DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_dat.dbf' AUTOEXTEND ON;
ALTER DATABASE DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_lob.dbf' AUTOEXTEND ON;
ALTER DATABASE DATAFILE 'C:/oraclexe/app/oracle/oradata/XE/r6_idx.dbf' AUTOEXTEND ON;

CREATE USER KGY
IDENTIFIED BY KGY1
DEFAULT TABLESPACE R6_DAT
TEMPORARY TABLESPACE R6_TMP
QUOTA UNLIMITED ON R6_DAT
QUOTA UNLIMITED ON R6_IDX
QUOTA UNLIMITED ON R6_LOB
;

GRANT DBA, RESOURCE, CONNECT TO KGY;
