CREATE TABLE MARKET_ITEM (
	MODULEID NUMBER(8, 0),
	CLASSID NUMBER(8, 0),
	SPID NUMBER(8, 0),
	APPID NUMBER(8, 0),
    TENANTID NUMBER(4, 0),
    ITEMID NUMBER(8, 0) NOT NULL,
	LEVEL1 NUMBER(8, 0),
	LEVEL2 NUMBER(8, 0),
	LEVEL3 NUMBER(8, 0),
	LEVEL4 NUMBER(8, 0),
	TITLE VARCHAR2(1000),
	AUTH_USERID NUMBER(8, 0),
	AUTH_NAME VARCHAR2(1000),
	AUTH_DISP VARCHAR2(1000),
	RGST_USERID NUMBER(8, 0),
	RGST_NAME VARCHAR2(1000),
	CONTENT	CLOB,
	OPN_CNT NUMBER(4, 0) DEFAULT 0 NOT NULL,
	STATUS NUMBER(4, 0) DEFAULT -1 NOT NULL,
	STATUS_DELETE NUMBER(4, 0),
	LAST_UPDT DATE DEFAULT SYSDATE,
	FILE_EXT VARCHAR2(10),
	KMID NUMBER(8, 0),
	SCRT_LEVEL NUMBER(4, 0) DEFAULT 0 NOT NULL,
	ISVISB NUMBER(1, 0) DEFAULT 0 NOT NULL,
	RGST_DATE DATE DEFAULT SYSDATE,
	STEP NUMBER(8, 0) DEFAULT 0 NOT NULL,
	CSTM_FIELD1	VARCHAR2(500),
	CSTM_FIELD2	VARCHAR2(500),
	CSTM_FIELD3	VARCHAR2(4000),
	ISMOBILE NUMBER(1, 0) DEFAULT 0 NOT NULL,
	SYMPATHY_CNT NUMBER(4, 0) DEFAULT 0 NOT NULL,
	ISBEST	NUMBER(1, 0) DEFAULT 0,
	ISPRICEBEST	NUMBER(1, 0) DEFAULT 0,
	START_TIME	DATE DEFAULT SYSDATE,
	END_TIME	DATE DEFAULT SYSDATE,
	ISDONATE	NUMBER(1, 0) DEFAULT 0,
	START_PRICE	NUMBER(8, 0),
	MINIMUM_AMOUNT	NUMBER(8, 0),
	IMMEDIATE_PURCHASE	NUMBER(8, 0),
	CURRENT_PRICE	NUMBER(8, 0),
	PURCHASE_TIME	DATE,
	PURCHASE_PRICE	NUMBER(8, 0),
	PURCHASE_USERID	NUMBER(8, 0),
	PURCHASE_NAME	VARCHAR2(2000),
	PURCHASE_DISP	VARCHAR2(1000),
	PURCHASE_COMPLETE	DATE DEFAULT SYSDATE,
	SALES_COMPLETE	DATE DEFAULT SYSDATE,
	READ_CNT NUMBER(8, 0) DEFAULT 0 NOT NULL
) TABLESPACE R6_DAT;

CREATE TABLE MARKET_ITEM_BIDDING (
	BIDDINGID	NUMBER(8, 0)	NOT NULL,
	ITEMID	NUMBER(8, 0),
	USERID	NUMBER(8, 0),
	USER_DISP VARCHAR2(1000),
	NAME	VARCHAR2(2000),
	BIDDING_TIME	DATE,
	BIDDING_PRICE	NUMBER(8, 0),
	ISBIDDING_FINAL	NUMBER(1, 0) DEFAULT 0,
	ISBIDDING_CANCEL	NUMBER(1, 0) DEFAULT 0
) TABLESPACE R6_DAT;

CREATE TABLE MARKET_ITEM_FILE (
	FILEID NUMBER(8, 0) NOT NULL,
	ITEMID NUMBER(8, 0) NOT NULL,
	FILE_NAME VARCHAR2(500),
	FILE_SIZE NUMBER(16, 0) DEFAULT 0 NOT NULL,
	DNLD_CNT NUMBER(8, 0) DEFAULT 0 NOT NULL,
	SAVE_CODE NUMBER(4, 0) DEFAULT -1 NOT NULL,
	SAVE_PATH VARCHAR2(500)
) TABLESPACE R6_DAT;

CREATE TABLE MARKET_ITEM_OPN (
    OPNID NUMBER(8, 0) NOT NULL,
	GID NUMBER(8, 0) NOT NULL,
	ITEMID NUMBER(8, 0) NOT NULL,
	USERID NUMBER(8, 0),
	USER_NAME VARCHAR2(1000),
	USER_DISP VARCHAR2(1000),
	RGST_USERID NUMBER(8, 0),
	RGST_DATE DATE DEFAULT SYSDATE,
	CONTENT VARCHAR2(4000),
	ISMOBILE NUMBER(1, 0) DEFAULT 0 NOT NULL
) TABLESPACE R6_DAT;


CREATE TABLE MARKET_ITEM_SYMPATHY (
    ITEMID NUMBER(8, 0) NOT NULL,
	USERID NUMBER(8, 0) NOT NULL,
	USER_NAME VARCHAR2(1000),
	USER_DISP VARCHAR2(1000),
	SYMP_TYPE NUMBER(4, 0) DEFAULT -1 NOT NULL,
	INST_DATE DATE DEFAULT SYSDATE NOT NULL
) TABLESPACE R6_DAT;

CREATE TABLE MARKET_ITEM_TAG (
    ITEMID NUMBER(8, 0) NOT NULL,
	TAG VARCHAR2(100),
	ITEM_DATE DATE,
	SEQ_ORDER NUMBER(8, 0) DEFAULT 0 NOT NULL,
	ISVISB NUMBER(1, 0) DEFAULT 0 NOT NULL
) TABLESPACE R6_DAT;

CREATE TABLE MARKET_ITEM_SCRT (
	SEQ_ORDER NUMBER(8, 0) DEFAULT 0 NOT NULL,
	ITEMID NUMBER(8, 0) NOT NULL,
	TITLE VARCHAR2(1000),
	ISVISB NUMBER(1, 0) DEFAULT 0 NOT NULL,
	ISCOMP NUMBER(1, 0) DEFAULT 0 NOT NULL,
	XID NUMBER(17, 0)
) TABLESPACE R6_DAT;

CREATE TABLE MARKET_ITEM_READ (
	ITEMID NUMBER(8, 0) NOT NULL,
	USERID NUMBER(8, 0) NOT NULL,
	CMD_CODE NUMBER(10, 0) DEFAULT -1 NOT NULL,
	INST_DATE DATE DEFAULT SYSDATE NOT NULL,
	USER_NAME VARCHAR2(1000),
	USER_DISP VARCHAR2(1000),
	STAT_FLAG NUMBER(1, 0) DEFAULT 0 NOT NULL
) TABLESPACE R6_DAT;


--마켓아이템 ITEMID PK 제약조건
ALTER TABLE MARKET_ITEM ADD CONSTRAINT XPK_MARKET_ITEM PRIMARY KEY (ITEMID)
USING INDEX TABLESPACE R6_IDX; 
--입찰정보 BIDDINGID PK 제약조건
ALTER TABLE MARKET_ITEM_BIDDING ADD CONSTRAINT XPK_MARKET_ITEM_BIDDING PRIMARY KEY (BIDDINGID)
USING INDEX TABLESPACE R6_IDX; 
--첨부파일 FILEID PK 제약조건
ALTER TABLE MARKET_ITEM_FILE ADD CONSTRAINT XPK_MARKET_ITEM_FILE PRIMARY KEY (FILEID)
USING INDEX TABLESPACE R6_IDX; 
--마켓아이템 의견 OPNID PK 제약조건
ALTER TABLE MARKET_ITEM_OPN ADD CONSTRAINT XPK_MARKET_ITEM_OPN PRIMARY KEY (OPNID)
USING INDEX TABLESPACE R6_IDX; 
--마켓아이템 공감 ITEMID,USERID 제약조건
ALTER TABLE MARKET_ITEM_SYMPATHY ADD CONSTRAINT XPK_MARKET_ITEM_SYMPATHY PRIMARY KEY (ITEMID, USERID)
USING INDEX TABLESPACE R6_IDX; 

--마켓아이템 TENANTID FK 제약조건
ALTER TABLE MARKET_ITEM ADD CONSTRAINT TENANT_R_MARKETITEM FOREIGN KEY (TENANTID)
REFERENCES TENANT (TENANTID);
--마켓아이템 CLASSID FK 제약조건
ALTER TABLE MARKET_ITEM ADD CONSTRAINT WBCLASS_R_MARKETITEM FOREIGN KEY (CLASSID)
REFERENCES WB_CLASS (CLASSID);
--마켓아이템 MODULEID FK 제약조건
ALTER TABLE MARKET_ITEM ADD CONSTRAINT WBMODULE_R_MARKETITEM FOREIGN KEY (MODULEID)
REFERENCES WB_MODULE (MODULEID);
--입찰정보 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_BIDDING ADD CONSTRAINT TENANT_C_MARKETITEMBIDDING FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;
--입찰정보 USERID FK 제약조건
ALTER TABLE MARKET_ITEM_BIDDING ADD CONSTRAINT TENANT_C_MARKETITEMBIDDING FOREIGN KEY (USERID)
REFERENCES HR_USER (USERID) ON DELETE CASCADE;
--파일 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_FILE ADD CONSTRAINT MARKETITEM_C_FILE FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;
--의견 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_OPN ADD CONSTRAINT MARKETITEM_C_OPN FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;
--보안 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_SCRT ADD CONSTRAINT MARKETITEM_C_SCRT FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;
--공감 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_SYMPATHY ADD CONSTRAINT MARKETITEM_C_SYMPATHY FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;
--태그 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_TAG ADD CONSTRAINT MARKETITEM_C_TAG FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;
--조회 ITEMID FK 제약조건
ALTER TABLE MARKET_ITEM_READ ADD CONSTRAINT MARKET_C_READ FOREIGN KEY (ITEMID)
REFERENCES MARKET_ITEM (ITEMID) ON DELETE CASCADE;


--인덱스 설정
CREATE INDEX XIE_MARKETITEM_AUTHUSERID ON MARKET_ITEM (AUTH_USERID, STATUS) TABLESPACE R6_IDX;
CREATE INDEX XIE_MARKETITEM_RGSTUSERID ON MARKET_ITEM (RGST_USERID, STATUS) TABLESPACE R6_IDX;
CREATE INDEX XIF_MARKETITEM_CLASSID ON MARKET_ITEM (CLASSID) TABLESPACE R6_IDX;
CREATE INDEX XIF_MARKETITEM_MODULEID ON MARKET_ITEM (MODULEID, APPID) TABLESPACE R6_IDX;
CREATE INDEX XIF_MARKETITEM_TENANTID ON MARKET_ITEM (TENANTID) TABLESPACE R6_IDX;
CREATE UNIQUE INDEX XIF_MARKETITEMFILE_ITEMID ON MARKET_ITEM_FILE (ITEMID, FILEID) TABLESPACE R6_IDX;
CREATE UNIQUE INDEX XIF_MARKETITEMMOPN_GID ON MARKET_ITEM_OPN (ITEMID, GID, OPNID) TABLESPACE R6_IDX;
CREATE UNIQUE INDEX XIF_MARKETITEMOPN_ITEMID ON MARKET_ITEM_OPN (ITEMID, OPNID) TABLESPACE R6_IDX;
CREATE INDEX XIF_MARKETITEMSCRT_ITEMID ON MARKET_ITEM_SCRT (ITEMID) TABLESPACE R6_IDX;
CREATE INDEX XIE_MARKETITEMTAG_ISVISB ON MARKET_ITEM_TAG (ISVISB) TABLESPACE R6_IDX;
CREATE INDEX XIE_MARKETITEMTAG_ITEMID ON MARKET_ITEM_TAG (ITEMID) TABLESPACE R6_IDX;
CREATE INDEX XIE_MARKETITEMTAG_TAG ON MARKET_ITEM_TAG (UPPER(TAG)) TABLESPACE R6_IDX;
CREATE INDEX XIE_BDITEMREAD_ITEMID ON MARKET_ITEM_READ (CMD_CODE, ITEMID, INST_DATE) TABLESPACE R6_IDX;
CREATE INDEX XIF_BDITEMREAD_ITEMID ON MARKET_ITEM_READ (ITEMID) TABLESPACE R6_IDX;